### ISSUE TITLE
People can use lava and water buckets

### ISSUE THREAD

**Issue by MRCartm0n** [World-of-Tomorrow/NoItem#1]
Some ranks on my server can't use lava and water buckets but we found a bug how they still can use them. When they have a empty spot in the inventory bar and they throw the bucket on the ground, it gets automatically picked up and they can use it.

**Comment by just-push-it** [comment]
checking..

**Comment by just-push-it** [comment]
Ok this _should_ be fixed in [build #61](http://ci.worldoftomorrow.net/job/NoItem/61/0)
(Sorry for the long delay, but I had things to attend to )

**Comment by MRCartm0n** [comment]
"long delay" ... by other authors I would wait months till I would get a simple asnwer lol.

Thanks alot again for your help and great work!
