### ISSUE TITLE
Banning Item #128 Also Bans 128.1

### ISSUE THREAD

**Issue by milkymilkway** [World-of-Tomorrow/NoItem#12]
Permissions: http://pastie.org/4333375

The permission "- noitem.nocraft.128" also blocks 128.1

*****I added 128.all but 128 still blocks both even without 128.all

**Comment by just-push-it** [comment]
See how easy that was? Now. Of course 128.1 is going to be blocked because you also have 128.all there. Remove that and try again.

**Comment by milkymilkway** [comment]
Like I said Nala. Even with 128.all not there it still blocks 128:1 and 128. With just 128 it will still block both. It use to not do this I dont  think. Any ideas?

**Comment by just-push-it** [comment]
Fixed in build #114 http://ci.worldoftomorrow.net/job/NoItem/114/
