### ISSUE TITLE
Add noopen node.

### ISSUE THREAD

**Issue by 1986anthony** [World-of-Tomorrow/NoItem#17]
Could you add a node to prevent the opening of things like furnaces or chests. I wish to use to prevent the opening of some of the tekkit blocks.

**Comment by just-push-it** [comment]
Already added to nouse in 2.0.6 :) You can try out a development build if you want. ( Will probably have some bugs, so if you find one, just tell me! )

Also, 2.0.6 will include support for custom furnaces and workbenches.
