### ISSUE TITLE
Tekkit Crafting Tables not working

### ISSUE THREAD

**Issue by eagle4life69** [World-of-Tomorrow/NoItem#18]
Great plugin I am having 1 issue, I want to restrict crafting of certain items in Tekkit 3.1.1 It works with regular crafting tables but does not in the tekkit Project Table, Automatic Crafting Table or MK3 Crafting Table.

I am not sure how to you can see what those tables do but I would love to have it block those instead of me having to limit those (they make life easier)

Thanks again
Eagle

**Comment by just-push-it** [comment]
This issue is being addressed in the next release with the ability to define custom blocks.

**Comment by eagle4life69** [comment]
Thanks any guess on the next release? If you do this your plugin will be the only one that works

**Comment by just-push-it** [comment]
Probably pretty soon. However development has been a bit slow as of late, because I'm remaking my entire server for 1.3, trying to find a job, and have 3 other projects to work on! But I haven't forgotten about it :)

**Comment by eagle4life69** [comment]
Thanks. Me and my server appreciate it. Good luck on the job front Thanks again (and just release this fix for me ;) )
