### ISSUE TITLE
Shift + click item in hotbar

### ISSUE THREAD

**Issue by cecell** [World-of-Tomorrow/NoItem#2]
I'm opening my inventory and shift + clicking on something in my hotbar to move it to my inventory and this is the error i'm getting:

http://dl.dropbox.com/u/5802995/2012-05-29_21.39.45.png

I have no armor on and I have the permissions node '*'
I'm using PEX

I am not op.

I'm running CB 1.2.5-R3.0

Thanks
Cecell

**Comment by just-push-it** [comment]
Okay, I am looking into it now

Also, what version / build are you running?

**Comment by just-push-it** [comment]
Okay I can't seem to recreate this with the latest build. Try a development build and see if that fixes your problems

**Comment by cecell** [comment]
OK it is permissions related as it is only happening to players that have the '_' permissions node (i.e. me).  I just added that node to my alt and it did the same thing to him.  I just added '-noitem._' to my permissions node and it stopped the problem.  You might want to add a note about that as I can see other admins being like wtf? lol. Again, Great plugin!
