### ISSUE TITLE
Tekkit

### ISSUE THREAD

**Issue by jammedgears** [World-of-Tomorrow/NoItem#20]
Does this work with the Tekkit mod?

**Comment by just-push-it** [comment]
Yes, but not with everything. (Yet!)

**Comment by jammedgears** [comment]
What does it not work with?

**Comment by jammedgears** [comment]
Nevermind if theres any problem I'll tell you

**Comment by eagle4life69** [comment]
One of the Things he has said coming in the new version will be the ability to block the crafting of items on other Workbench types (like: Project table, Automatic Crafting table) and at last check Tekkit Furnaces will be blocked too if you wanted to.

**Comment by just-push-it** [comment]
Well basically there will be a format to add custom blocks to the configuration. so like:
CustomBlocks:
    BlockName:
        id: 1337
        data: 42
        type: furnace
        fuel-slots:
            - 0
            - 1
            - 2
        item-slots:
            - 3
            - 4
            - 5
            - 6

**Comment by just-push-it** [comment]
of course, I will probably have a page devoted to pre-made configurations for different blocks that way you can just copy and paste them.

**Comment by AXMAN43** [comment]
Hello, what if an item isn't a furnace or workbench such as a Sword or just a block.
