### ISSUE TITLE
Should this work?

### ISSUE THREAD

**Issue by Robert09** [World-of-Tomorrow/NoItem#22]
```
- noitem.nouse.27573 and would that work with group manager? Can you make a tutorial for the config files?
```

**Comment by just-push-it** [comment]
Why do you need a tutorial for the config file? It is pretty straightforward. Also, I don't use or test with groupmanager but I would think so.

**Comment by Robert09** [comment]
Well the reason I need a tutorial is because when ever I add the
permissions it does not work at all
