### ISSUE TITLE
Tekkit Item restrictions

### ISSUE THREAD

**Issue by Muzixs** [World-of-Tomorrow/NoItem#26]
Hi, im using a tekkit server an im trying to disable most of the use of EE items, mainly the collectors. MY problem is that when i put in "noitem.nouse.126" i get it so where i cant place ANY of the 126:\* items. I've made sure i was doing ti right an did 'noitem.nouse.126.1" an was able to disable use of that one item an not the rest. i also tried to do "noitem.nouse.126.0" (might have been derpy of me) but still nothing. Is there something im missing?

**Comment by just-push-it** [comment]
Try noopen instead :) It will just prevent them from opening the condensers. That combine with other permissions can effectively make it useless to them.

**Comment by Muzixs** [comment]
Ah ur a godsend, the noopen is working great and its not reading noitem.noopen.126 as noitem.noopen.126.all. I noticed the build was for 1.3.1 but it worked on tekkit with a bukkit build of 1.2.5. Is it safe to say that your lasest build will works as well?

**Comment by just-push-it** [comment]
Yes, since I use the Bukkit API it will work with almost any Bukkit version, but I may need to update it when Tekkit updates because I do hook directly into that.

**Comment by just-push-it** [comment]
Also, make sure you check back on the project tomorrow, I had uploaded the wrong file for the 3rd beta release! I should read better. That version should fix the philo stone problem :)

**Comment by Muzixs** [comment]
Great, thanks so much. Marvelous plugin, keep it up.
