### ISSUE TITLE
No Debugging

### ISSUE THREAD

**Issue by Agentmass** [World-of-Tomorrow/NoItem#27]
Sorry, found a few more bugs.

The development builds do not have a working debug mode. I turned it on and I saw nothing in console. Worked fine with the stable builds.

The Ender Chest from Tekkit are not considered real blocks. I have it listed as one of the blocks to not be able to be placed but you are still able to place it. This most likely may not be fixable/ too much hassle to fix but I listed it anyways.

**Comment by just-push-it** [comment]
For the debugging, restart the server after you turn debugging on. It registers a special class for debugging. I suppose I could fix that, which I probably will...eventually.

I will look into the ender chest thing though.

**Comment by Agentmass** [comment]
I did restart the server. Maybe there is another plugin screwing it up. The only reason I needed it was to check how to disable someone from changing the colors of the wool on top of the enderchests.

**Comment by just-push-it** [comment]
Hmm I will look into that. but it should work.

**Comment by just-push-it** [comment]
Okay I changed the debugging so it should work fine after /noitem reload now.

I am checking the enderchest thing tomorrow.

**Comment by just-push-it** [comment]
Yeah I just think it just doesn't fire a block place event. I can't really do anything about that except hope it is fixed in the next Tekkit version.
