### ISSUE TITLE
Tekkit Item node grouping issue

### ISSUE THREAD

**Issue by Muzixs** [World-of-Tomorrow/NoItem#29]
I have my permissions set up to block the following but once i go past the noitem.nouse.126|... members can still open and use items blocked. Did i set this up right?

Groups:
  Standard:
    permissions:
    - -bukkit.command.plugins
    - essentials.spawn
    - essentials.rules
    - essentials.motd
    - essentials.list
    - essentials.balance
    - essentials.help
    - essentials.balancetop
    - essentials.pay
    - essentials.worth
    - essentials.afk
    - essentials.mail
    - essentials.motd
    - essentials.msg
    - essentials.ignore
    - essentials.mail.send
    - essentials.sethome
    - herochat.join.global
    - herochat.leave.global
    - herochat.speak.global
    - herochat.autojoin.global
    - essentials.gamemode
  Default:
    default: true
    permissions:
    - noitem.nocraft.177|177.256|177.512|179|194.2|194.4|214|216|216.1|216.2|216.3|239|237|250.15
    - noitem.noopen.126|126.1|126.2|126.3|126.4|126.5|126.6|126.7
    - noitem.noplace.237|226.10|226.11
    prefix: '&7[Default]  '
    inheritance:
    - standard

**Comment by just-push-it** [comment]
Read PEX documentation. - noitem.noplace.(237|226.10|226.11)

**Comment by Muzixs** [comment]
Ah the parenthesis >.< sorry about that. Thanks!
