### ISSUE TITLE
Damaged Flint and Steel

### ISSUE THREAD

**Issue by MRCartm0n** [World-of-Tomorrow/NoItem#3]
I found out that players can use damaged flint and steel when they aren't allowed to.

**Comment by just-push-it** [comment]
This seems like another one of those special cases I forgot to cover. Working on it :)

**Comment by just-push-it** [comment]
Ok so i have the fix but I did not get to push it so didn't get built, I will when I get home though

**Comment by just-push-it** [comment]
Okay, should be fixed in [build #66](http://ci.worldoftomorrow.net/job/NoItem/66/), care to test it for me and find out?

**Comment by MRCartm0n** [comment]
I will as soon as I get the chance to restart the server and update te plugin. Thanks for the fast help again :)

**Comment by MRCartm0n** [comment]
Ok, works for me :)

**Comment by just-push-it** [comment]
Cool, let me know if you have any issues :)
