### ISSUE TITLE
Shift Clicking Into Furnaces

### ISSUE THREAD

**Issue by orc7719** [World-of-Tomorrow/NoItem#32]
Players that are blocked from cooking raw food in a furnace can just bypass it by shift clicking the food into the furnace

**Comment by just-push-it** [comment]
Version?
Permissions? 
Minecraft version?
You can't give me no information and about that stuff and expect me to fix an issue

**Comment by orc7719** [comment]
bukkit version - 1.3.1-R2.0
noitem version -  2.0.6
the permission nodes im using are
    - noitem.nocook.319
    - noitem.nocook.349
    - noitem.nocook.363
    - noitem.nocook.365
and its in minecraft 1.3.2

**Comment by just-push-it** [comment]
I will look into it, i suspect you to be right xD

**Comment by just-push-it** [comment]
As there has been no more feedback, I am closing the issue. @orc7719, you may re-open this ticket if the issue still exists.
