### ISSUE TITLE
Select ranks cannot place items

### ISSUE THREAD

**Issue by ghost** [World-of-Tomorrow/NoItem#33]
I have a ranking system set up to where only certain ranks can use certain items or wear certain pieces of armor. As a note, this is a tekkit server. I am using Permission Ex for my perms folder.  To keep it simple, I have noitem.nocraft.153 which is a quarry, but I have - -noitem.nocraft.153 later on for another rank, which should allow them to create a quarry.

I am also running Tekkit version 3.1.2
I am using noitem 2.0.6

Here is a paste bin of my current perms file:  http://pastebin.com/vWCAhgcy

**Comment by just-push-it** [comment]
Okay, so you are saying that even though you remove the node later on, it still will not let them craft the quarry?

**Comment by ghost** [comment]
Correct, and the same is happening with every thing I remove later on. I cannot have the players wear armors I blocked, use tools I blocked etc etc.

**Comment by just-push-it** [comment]
Weird, others have used this type of thing in the past without problems.. I will investigate the possibility of it being a new issue with 2.0.6 and if you find out that it is a just a silly mistake on your part, just tell me so I don't frustrate myself trying to fix the problem xD

**Comment by ghost** [comment]
Haha, oh trust me, I have been trying things. Do you think it may be an issue with another plugin(s) that I am using? I have two other plugins which have the potential to disable items. I use Disable Craft, which has a scanner to scan for banned items and remove them from players inventories. I use this for globally banned items, like nukes. I also use tekkitrestrict for its limiter function, so I can limit how many quarries a player can have at one time to save resources.

**Comment by just-push-it** [comment]
It may, but I doubt it. Although I am glad to say that pretty soon I am adding a nohave node which stop the player from ever getting the item.

**Comment by ghost** [comment]
Oh, that will be nice for the future. I will be running some tests later today to see if it may be a plugin conflict.

**Comment by ghost** [comment]
One thing I have noticed, as I was running through my ranks with my secondary account, is that I do not get the chat warnings when I try to craft some thing that the rank should be allowed too. Normally I get the chat message "You are not allowed to craft XYZ", but when I am the rank that is supposed to be able to craft the item the chat message is not there.

**Comment by ghost** [comment]
Actually, I fixed the quarry issue. I had left an old perm node from modifyworld blocking quarries. I also noticed I forgot to allow certain ranks to wear certain armors, so it seems that it was a stupid mistake on my end causing issues. I am still running through all of my ranks checking things.

**Comment by just-push-it** [comment]
Okay so you fixed it? xD

**Comment by ghost** [comment]
Yea, it seems fixed. It was just stupid simple mistakes I made after pulling an all nighter.
_note to self_ do not work on perms with no sleep :| 
Thank you for trying to help me though, it is really appreciated.

**Comment by just-push-it** [comment]
No problem, things like this happen xD
