### ISSUE TITLE
Mouse Wheel Bug

### ISSUE THREAD

**Issue by Muzixs** [World-of-Tomorrow/NoItem#34]
I have the node(s) nocraft and nohold for certain items to banned and or craft them as well as share them with other players. I did some intensive fiddling with the plugin an found this bug where if ur fast enough on the mouse wheel or but just hitting the top number keys to the item u can trick the plugins an hold the item as well as placing it. Now i guessing i could just do noplace but i just wanted to get this bug out there an known as well as fixed. 

I have a video uploading atm, idk if when u get this it will be done but yea, have a look at it.

http://youtu.be/YQMGE0M33G4

Edit: Ive just realized that i was in gamemode 1 while doing this, an for some reason it glitches out due to infinite items in creative; im guessing. Though is isnt exactly a problem, i had planed to allow high level donators to use gm while disabling the ability to place those blocks along with others. I would still like to have my high level donators use gm but this isnt really a bug so much as request, so up to you =D. 

PS: I love how this plugin is coming along.

**Comment by just-push-it** [comment]
I will look into it, thanks for the information! :)

**Comment by just-push-it** [comment]
Can you confirm that this still happens with a development build? If not, then I can just close this!

**Comment by just-push-it** [comment]
Closed - No response from submitter on whether the issue still exists.
