### ISSUE TITLE
Issue with LWC protections

### ISSUE THREAD

**Issue by Tetdoss** [World-of-Tomorrow/NoItem#36]
With the last version of NoItem, we can open LWC locked furnace and LWC locked door :/

Thanks :)

**Comment by just-push-it** [comment]
I am not really sure how this is possible, I never actually set an event cancellation to false. I will however check into this.

**Comment by just-push-it** [comment]
Actually on second glance, I see the problem. It will be fixed very soon!

**Comment by just-push-it** [comment]
NoUseListener - lines 66 and 120

**Comment by Tetdoss** [comment]
Good job, when can I have the fixed version ?

**Comment by just-push-it** [comment]
Whenever you want :P http://ci.worldoftomorrow.net/job/NoItem/
