### ISSUE TITLE
Not all Tekkit bags being blocked

### ISSUE THREAD

**Issue by eagle4life69** [World-of-Tomorrow/NoItem#38]
I have this command in my permissions file - noitem.nocraft.27562.all
and after running some tests the following colors are not being blocked Orange, Magenta, Grey, Cyan, and Purple

I would love to allow my members to craft white which is item 27562 the other colors have data values 1-15

Please help block all bags but white

**Comment by just-push-it** [comment]
Please follow these steps:
1) Make sure you have the latest version of NoItem
2) If so, run the command "noitem debug dump" in the console
3) Post the contents of debug_dump.txt to http://pastie.org/ or similar and copy the link here
3.1) debug_dump.txt is in the plugin folder
4) Post the **relevant** permissions to a seperate pastie as well.

**Comment by eagle4life69** [comment]
when you mean latest do you include the beta's as latest? I am on 2.0.6 also how can I run noitem debug dump if All I have is McMyAdmin?

**Comment by just-push-it** [comment]
Yes I mean the 2.0.7 beta. .. Just run it?

**Comment by eagle4life69** [comment]
here is my Dump file
http://pastie.org/4889891
here is my customblock file
http://pastie.org/4889897

I am using - noitem.nocraft.27562.all for permissions even though I would like to only restrict colored bags 1-15 with white being with no data value

If you need my permissions x file let me know

**Comment by just-push-it** [comment]
Checking into this now.

**Comment by just-push-it** [comment]
I seem to be able to block bags on the vanilla crafting table and any configured blocks. As I can not seem to reproduce this, I am closing the ticket.
