### ISSUE TITLE
Tekkit Problem'

### ISSUE THREAD

**Issue by LadySmith** [World-of-Tomorrow/NoItem#39]
I got a tekkit server and using NoItem. But when i add eg. noitem.nocraft.27581 it can be craftable i cant block it only nohold and nowear works in my server. Some items have data codes im adding it like noitem.nocraft.126.10 but it wont works too.

Please help me to solve this.

Edit: This is EE mod.

**Comment by just-push-it** [comment]
Things I need from you:
1) NoItem version (not just "latest")
2) Relevant permissions (use pastie)
3) CustomBlocks.yml (use pastie)

**Comment by LadySmith** [comment]
NoItem version is 2.0.5 [Tekkit's Bukkit using 1.2.5]
I'm using PermissionEx from McMyAdmin: http://pastie.org/private/9fikvqhi5vo1b06huqg7vg
My NoItem folder don't have a CustomBlocks.yml

**Comment by just-push-it** [comment]
Well then update silly! 2.0.6 is the latest recommended version. there is a 2.0.7 beta build up as well.

**Comment by LadySmith** [comment]
Can i use latest build in tekkit?

**Comment by just-push-it** [comment]
Of course.
