### ISSUE TITLE
Add no drop permissions

### ISSUE THREAD

**Issue by cecell** [World-of-Tomorrow/NoItem#4]
Add ability to prevent players from dropping certain items.  

Thanks!

**Comment by just-push-it** [comment]
Good idea, I will do it tomorrow :)

**Comment by nala4** [comment]
Okay I have a development build out, test it out and see if you find any bugs before I close the ticket :)

**Comment by just-push-it** [comment]
Haha just realized I was on the wrong account when I posted that
