### ISSUE TITLE
Disable Right Click

### ISSUE THREAD

**Issue by eagle4life69** [World-of-Tomorrow/NoItem#42]
I have just ran into the issue where right clicking with Dark Matter tools in a restricted area can destroy the blocks. So I would like to ask if you can make it so they can not Right click with an item. This would also be useful with the philosophers stone disabling right click but allowing to hold in hand and pressing C.

Let me know

**Comment by just-push-it** [comment]
Hmm, I may be able to with PlayerInteract, it has a RIGHT_CLICK_AIR enum but I'm not sure if it is fired...
