### ISSUE TITLE
Some functions not working in world, but do work in end

### ISSUE THREAD

**Issue by Weldothewise** [World-of-Tomorrow/NoItem#44]
Cant use the 'use' and 'wear' functions in the main world, but they work fine in the end.
Running this on a craftbukkit 1.3.2 server

(p.s just wanna say, this plugin is great! Keep up the good work)

**Comment by just-push-it** [comment]
Please reply with the following:
- Your NoItem version
- Your permissions manager
- Any relevant permissions files as a gist link ( https://gist.github.com/ )

If your NoItem version is not **at least** 2.0.6, update NoItem. If it is 2.0.6 **or** 2.0.7 Beta 1 (2.0.7-SNAPSHOT-193), then update to the **latest** beta and run the command "noitem debug dump" and paste the output of the debug_dump.txt file (in the plugin folder) to https://gist.github.com/ and include the link.

**Comment by Weldothewise** [comment]
NoItem Ver. 2.0.7-Snapshot
Perms: GroupManager

Debug and groups.yml for GroupManager:

https://gist.github.com/3891914

(Not sure how to embed, bit of a noob)

**Comment by just-push-it** [comment]
Thanks for the information! I will look into the matter.

**Comment by Weldothewise** [comment]
Seems to be working now, im running a 1.4.2 server and still using the same version of NoItem

**Comment by just-push-it** [comment]
Weird...
