### ISSUE TITLE
Buildcraft quarry mechanical arm entity

### ISSUE THREAD

**Issue by soulgriever** [World-of-Tomorrow/NoItem#46]
Hi I use your plugin and love it, however It cannot process the blockbreakevent from buildcraft's entity for the mechanical arm for the quarry. I was wondering if their is anyway to patch this or ignore the entity thanks in advance and here is a copy of the error log
http://pastebin.com/DzeVnY4X

**Comment by just-push-it** [comment]
Hmm, I will look into this. Where this is a problem with one block there is likely a problem with another somewhere >.>

**Comment by soulgriever** [comment]
could u perhaps do something like this? https://github.com/mung3r/ecoCreature/commit/89c43d9e7885e02f202d7804dcadad8deb62620f
