### ISSUE TITLE
Brewing not blocked when ingredients are put in brewing stand by shift-clicking.

### ISSUE THREAD

**Issue by Mangerman** [World-of-Tomorrow/NoItem#49]
Tested on clean Craftbukkit 1.4.2 R0.2 installation with PEX, Vault and NoItem 2.0.7 Build #212.

When placing the ingredients of a blocked potion into the brewing stand manually with your mouse (dragging), NoBrew works like a charm and blocks the potion.

However, when you place the ingredients into the brewing stand by shift-clicking on them in your inventory or quickslots, the potion is no longer blocked and it will be brewn. No errors show up in the console.

We have been experiencing this same issue (in hindsight) on our server since atleast 1.3.2 and NoItem 2.0.6, but we never figured out what was causing the NoBrew to fail until yesterday.

**Comment by just-push-it** [comment]
Okay, simple fix. I just need to add a shift click check to the event handler.

**Comment by just-push-it** [comment]
This issue is still being worked on.

**Comment by just-push-it** [comment]
re-wrote plugin. Re-open the issue if it still exists.
