### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by cecell** [World-of-Tomorrow/NoItem#5]
Doesn't look serious but figured I'd report it anyway.

07.06 05:55:42 [Server] INFO [NoItem] Configs loaded, events registered, and cake baked.
07.06 05:55:42 [Server] SEVERE  at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
07.06 05:55:42 [Server] SEVERE  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:432)
07.06 05:55:42 [Server] SEVERE  at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:197)
07.06 05:55:42 [Server] SEVERE  at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:368)
07.06 05:55:42 [Server] SEVERE  at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:381)
07.06 05:55:42 [Server] SEVERE  at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:238)
07.06 05:55:42 [Server] SEVERE  at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:256)
07.06 05:55:42 [Server] SEVERE  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
07.06 05:55:42 [Server] SEVERE  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
07.06 05:55:42 [Server] SEVERE  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
07.06 05:55:42 [Server] SEVERE  at net.worldoftomorrow.nala.ni.NoItem.onEnable(NoItem.java:19)
07.06 05:55:42 [Server] SEVERE  at net.worldoftomorrow.nala.ni.Updater.<init>(Updater.java:41)
07.06 05:55:42 [Server] SEVERE  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
07.06 05:55:42 [Server] SEVERE java.io.IOException: Server returned HTTP response code: 502 for URL: http://www.worldoftomorrow.net/noitem/latest.html

Thanks
Cecell

**Comment by just-push-it** [comment]
Yeah my server is down ATM , cloud flare sends a 502 and I guess I didn't handle that
