### ISSUE TITLE
Keep items on death without having the "noitem.ondeath.keep" permission

### ISSUE THREAD

**Issue by Mangerman** [World-of-Tomorrow/NoItem#50]
After running the /noitem claim command as an OP, you will retain all your items upon death from that moment on. This is without having the noitem.ondeath.keep permission. Despite not having that permission, you will basicly be locked in that "mode". The only way to fix it, that I have found, is deleting the player file in the world folder.

If you run the same command as a non-OP this will not happen.

Debug Dump

https://gist.github.com/4055953

**Comment by just-push-it** [comment]
I will look into this, but I suspect it will probably be relatively simple to fix. But since I am not at home right now I can't fix it xD

**Comment by Deathrey** [comment]
The items are also kept on death for every OP. If player does not have noitem.ondeath.remove permission, the items are also duplicated. Deopping a player afterwards does not remove the issue, server restart is required.

**Comment by just-push-it** [comment]
This feature is not implemented right now. If it exists once I re-implement it, re-open the ticket.
