### ISSUE TITLE
Shift Clicking Items bypasses the nocraft and nowear.

### ISSUE THREAD

**Issue by Toby-B** [World-of-Tomorrow/NoItem#51]
On my server i have it setup so users cant make or wear diamond armour (unless donator) this works if you just click the items. The problem is they can be crafted if you shift click the item, it automatically places in your inventory. This is the same for wearing the item, shift clicking it while in your inventory puts it on and doesnt deny access to this. Hope this can be resolved quickly, for now i guess i should just stop them having it completely. Bit of a pain! xD

**Comment by just-push-it** [comment]
Blocking crafting seems to be working fine. I did fix being able to shift click armor though.
