### ISSUE TITLE
Configurable OP bypass

### ISSUE THREAD

**Issue by nvx** [World-of-Tomorrow/NoItem#53]
Feature request to disable the implicit bypass of restrictions for operators.

A bit of clarification, setting noitem.allitems to false for an OP causes all items to become banned. Setting noitem.allitems to false for a non-OP however does nothing, as expected. I did a quick look in the source to see if I could spot where this behaviour was coming from but couldn't find it at a quick glance of Perms.java.

**Comment by just-push-it** [comment]
I re-wrote the entire plugin. If this is still an issue, please create a new ticket.
