### ISSUE TITLE
nouse on entities 

### ISSUE THREAD

**Issue by imjoebaker** [World-of-Tomorrow/NoItem#57]
Can you, or is there an existing way to do something like the following?
- noitem.nouse.269.on.cow
  Prohibits the use of the wheat to breed a cow.

I use this plugin heavily for a roleplay server and wish for only "farmers" to breed animals. This system would apply to seeds for chickens, carrots for pigs and so on.

Yes, I can use the nohold node, however that causing huge complications as people can no longer eat carrots. ect. 

No, I can not use nouse as it currently is. It just has no effect with breeding.

**Comment by just-push-it** [comment]
Yes, it should not be too difficult. But as you can see there is quite a bit to do atm and I don't have much time to do it. So this may be on the back burner for a bit. Sorry :/

**Comment by imjoebaker** [comment]
Ok thanks for getting back to me. I'm not sure how you would go about it, either as I suggested above or if it would require a new variable such as - noitem.nobreed 

I hope you find the time. I know a few who want this, as it is all to easy for an average "joe" to make TONES of animals which is very unrealistic and bad for rp.

**Comment by just-push-it** [comment]
Taken care of in the re-write of noitem
