### ISSUE TITLE
Add permission to specify left or right click interaction.

### ISSUE THREAD

**Issue by FalconHunter** [World-of-Tomorrow/NoItem#59]
Hey can I suggest this could you make 2 different types of permissions for left click and right click? I noticed the noitem.nouse.<item>[.data] and that is amazing and that is just what i need but i want to be able to disable right clicking of a tekkit item and allow left clicking of it could that be done in a new version of noitem that is compatible with 1.2.5?

**Comment by just-push-it** [comment]
Done. noitem.nointeract.[right|left].item.data
