### ISSUE TITLE
Immense lag

### ISSUE THREAD

**Issue by RyanSayer** [World-of-Tomorrow/NoItem#68]
30.12 16:00:17 [Server] INFO ... 19 more
30.12 16:00:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
30.12 16:00:17 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source)
30.12 16:00:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
30.12 16:00:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
30.12 16:00:17 [Server] INFO at net.worldoftomorrow.noitem.events.Listeners.onPlayerInteractEntity(Listeners.java:49)
30.12 16:00:17 [Server] INFO at net.worldoftomorrow.noitem.events.Handlers.handleInteractEntity(Handlers.java:189)
30.12 16:00:17 [Server] INFO at net.worldoftomorrow.noitem.permissions.PermMan.has(PermMan.java:37)
30.12 16:00:17 [Server] INFO at net.worldoftomorrow.noitem.permissions.PermMan.construct(PermMan.java:118)
30.12 16:00:17 [Server] INFO at net.worldoftomorrow.noitem.util.Messenger.getEntityName(Messenger.java:102)
30.12 16:00:17 [Server] INFO Caused by: java.lang.NullPointerException
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.Packet7UseEntity$$EnhancerByCGLIB$$8595b30c.handle(<generated>)
30.12 16:00:17 [Server] INFO at com.comphenix.protocol.injector.ReadPacketModifier.intercept(ReadPacketModifier.java:109)
30.12 16:00:17 [Server] INFO at com.comphenix.net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.Packet7UseEntity$$EnhancerByCGLIB$$8595b30c$$FastClassByCGLIB$$f176b43a.invoke(<generated>)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.Packet7UseEntity$$EnhancerByCGLIB$$8595b30c.CGLIB$handle$0(<generated>)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.Packet7UseEntity.handle(SourceFile:36)
30.12 16:00:17 [Server] INFO at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:1100)
30.12 16:00:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
30.12 16:00:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
30.12 16:00:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
30.12 16:00:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
30.12 16:00:17 [Server] INFO org.bukkit.event.EventException
30.12 16:00:17 [Server] SEVERE Could not pass event PlayerInteractEntityEvent to NoItem v3.0.1-233

**Comment by just-push-it** [comment]
Should have been fixed by e435ed0204892bead1de2ab88935dd137f5b7387
