### ISSUE TITLE
Full Tekkit Support

### ISSUE THREAD

**Issue by rom3ox** [World-of-Tomorrow/NoItem#71]
Hello, im testing NoItem 2.0.7 Snapshot on my tekkit server.

I can ban all tekkit items by id perfectly but i would like to use some kind of alias because we have a lot of noitem permissions on pex.

I think that the best option is some kind of alias.yml where we can assign the desired id to an alias like: 

RMSword: 27567

In this manner, everybody could create their own alias with the ids of their choice. 

I have seen that the class TekkitTool has already some alias for red matter tools so it would be easy to add the rest of tekkit aliases. I would try to decompile and recompile the jar adding the alias but i think that its better than you know the problem and the possible solution and recompile the jar with the original source.

If you need more information i would like to help to make this excelent plugin a better plugin for tekkit and vanilla servers.

We also test NoItem 3.0.2 on our tekkit server but its causes a lot of lag without throwing errors in the console. I also have tested CPU usage with nolagg and the origin of lag are all the events related to noitem (Blockbreak, blockplace,..)

**Comment by just-push-it** [comment]
NoItem 2.X is no longer supported or maintained. However a version of 3.X will be released for Tekkit when it has reached a stable release.

**Comment by just-push-it** [comment]
Since Tekkit is no longer maintained this is no longer relevant.
