### ISSUE TITLE
Text log or mysql log for registered events

### ISSUE THREAD

**Issue by rom3ox** [World-of-Tomorrow/NoItem#72]
I have seen that admins can be notified when somebody doesnt have noitem permissions.

It would be a great idea to log noitem events in a text file or in mysql database like this:

"PlayerName" try to "place" (Action) a "block/item" (id or name) in "world" "x y z" at "time"

It would be better even to have the option to log only the actions or items that we want to log. In tekkit server with a lot of items this would be a great help for admins to check who tried to use some item but cant.

**Comment by just-push-it** [comment]
I really have no plans to ever do this.
