### ISSUE TITLE
nointeract.* and nouse.* should include .right and .left

### ISSUE THREAD

**Issue by AnthonyAMC** [World-of-Tomorrow/NoItem#73]
The addition of right and left click blocking is indeed helpful, but the parent nodes should include the child. Having to specify .right and .left will triple the number of nodes required especially if utilizing whitelist mode.

**Comment by just-push-it** [comment]
Indeed, I will get to it eventually.

**Comment by just-push-it** [comment]
This issue will no longer be valid in the new version. right and left click specific functions will be separate features and therefore have their own options in the configuration, and permission nodes. (e.g. noitem.interactleft.stone)
