### ISSUE TITLE
noitem.allitems

### ISSUE THREAD

**Issue by AnthonyAMC** [World-of-Tomorrow/NoItem#74]
The 3.x series of NoItem no longer contains the noitem.allitems node. I'm sure the simple work around until it is brought back to life would be to create an alias in the bukkit permissions.yml file that contains all of the .\* nodes for NoItem. No rush on this, just a matter of convenience.

**Comment by just-push-it** [comment]
Just add "-noitem.*" to remove all NoItem permissions
