### ISSUE TITLE
Whitelist nobreak dupes

### ISSUE THREAD

**Issue by AnthonyAMC** [World-of-Tomorrow/NoItem#75]
Running in whitelist with no noitem.nobreak perms, some items show up twice in chat as if noitem is performing the perm check twice. Items i've noticed do this are redrose, dandelion, longgrass, torch, waterlily, crops, brownmushroom, redmushroom, redstonewire, redstonetorch, diodeblock... It seems like most things that have multiple states. Idk if this is an issue that produces a performance impact, but i figured you ought to know. It is likely that the same would be true for nointeract checks

**Comment by just-push-it** [comment]
This is because when you finish breaking something, you it cancels the event but you still hit the item again, so it fires another event which is cancelled, again.
