### ISSUE TITLE
Issue making some tools unholdable

### ISSUE THREAD

**Issue by clucky** [World-of-Tomorrow/NoItem#8]
I do not remember having an issue with this yesterday, however, I may have just not tested it. For some reason in my permission file I have noitem.nohold.283 set for group default, however, without even specifying -noitem.nohold.283 for any other player, everyone is able to hold it still. 

My permissions file can be found here: http://www.worldofclucky.net/noitem/permissions.yml
Here is my config: http://www.worldofclucky.net/noitem/config.yml
here is my list of plugins: http://www.worldofclucky.net/noitem/plugins.txt

The following tools I am having problems with everyone being able to hold:
283 = Gold Sword
258 = Iron Axe

**Comment by clucky** [comment]
EDIT: It seems that if I spawn an iron axe in, I can't hold it (it moves it from the slot that I have selected), however, if I use the iron axe I already had (before server restart) nothing happens. Does this plugin bind to certain tools? They're not enchanted. 

PS: I accidentally had two Noitems before in my /plugins folder, however, this problem still existed even after removing both of them and installing a new one then restarting my server. Could this have anything to do with it?

**Comment by clucky** [comment]
Ahha! I think it is the damage values on the tools. I'm going to add a .\* after the tool id and see if that changes anything

**Comment by clucky** [comment]
Yup, fixed it. You may want to specify this in your notes on the main page so I will leave this ticket open. Close it when your done with it. :)

**Comment by just-push-it** [comment]
Thanks for this info, I think this actually is a bug. I was supposed to handle all datavalues for tools in the code, but if this works I'm not complaining! I will leave this open until I find the cause.
