### ISSUE TITLE
insane console spam, permission null error

### ISSUE THREAD

**Issue by Glacksy** [World-of-Tomorrow/NoItem#81]
getting a lot of spam from this plugin, here's the error:

http://pastebin.com/4rDeQn7q

im using GroupManager and Vault if it matters

**Comment by AnthonyAMC** [comment]
Test dev build 240. An additional null check has been implimented.
http://ci.worldoftomorrow.net/job/NoItem/

**Comment by just-push-it** [comment]
@Glacksy can we get an update on whether or not you are still getting this error? We would love to help you, but we need feedback

**Comment by Glacksy** [comment]
seems to be fine, haven't had any spam since... well not noticeable spam :p
