### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by JohOply** [World-of-Tomorrow/NoItem#93]
Hello, i've an error which spam my logs :

> 15:19:42 [SEVERE] Could not pass event InventoryClickEvent to NoItem v3.0.3-242
> org.bukkit.event.EventException
> at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
> at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java:1177)
> at net.minecraft.server.v1_5_R2.Packet102WindowClick.handle(SourceFile:31)
> at net.minecraft.server.v1_5_R2.NetworkManager.b(NetworkManager.java:292)
> at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java:110)
> at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
> at net.minecraft.server.v1_5_R2.DedicatedServerConnection.b(SourceFile:30)
> at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:578)
> at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
> at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:474)
> at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:407)
> at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
> Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_4_R1/inventory/CraftItemStack
> at net.worldoftomorrow.noitem.events.Handlers.isCookable(Handlers.java:578)
> at net.worldoftomorrow.noitem.events.Handlers.handleNoCookInvClick(Handlers.java:460)
> at net.worldoftomorrow.noitem.events.Listeners.onInventoryClick(Listeners.java:68)
> at sun.reflect.GeneratedMethodAccessor222.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:601)
> at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
> ... 14 more

**Comment by just-push-it** [comment]
This is because you are using a NoItem version built for 1.4 and not 1.5.
