### ISSUE TITLE
Improvement : Disable items for put/take in container

### ISSUE THREAD

**Issue by JohOply** [World-of-Tomorrow/NoItem#94]
Hello !

I havn't see anything in your wiki to do this (so if i don't know read, say me and show me where i can find the information ^^)

With the 1.5 and the news features of the dispenser, there is news risks of grief with it (TNT, lighter, but also the lava from olders versions) So, i've think at a "simply" thing : prevent a player to put or take an item in a container (dispenser/hopper...) if he hasn't the permission.

A permission can be this for instance : noitem.nodeposit.[item][.data]

Thanks for reading and for this useful plugin !

**Comment by just-push-it** [comment]
VERSION

**Comment by JohOply** [comment]
3.0.3-b243 ; Bukkit 1.5.1 beta

But i don't see the link Oo
